apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: my-django-image:latest  # Build your image and push to a registry
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: DB_NAME
          value: "mydb"
        - name: DB_USER
          value: "abc"
        - name: DB_PASSWORD
          value: "123"
        - name: DB_HOST
          value: "postgres"
        - name: DB_PORT
          value: "5432"

---
apiVersion: v1
kind: Service
metadata:
  name: django
  namespace: todo-app
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: django
